spring:
    profiles:
        active: "dev"
    datasource:
        # This will make Sure for Dev enviornment data.sql never runs
        initialization-mode: never
        # Below is to make sure we don't keep our db connection open after 60 seconds of inactivity
        hikari:
           connection:
              timeout: 60000
           maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                id:
                    new_generator_mappings: false
logging:
    file: ./logs/application-debug.log
    level:
       root: WARN
       com:
          github:
             hbothra: INFO
       io:
          github:
             hbothra: INFO
       org:
          springframework: ERROR
          hibernate:
             SQL: WARN
             type:
                descriptor:
                   sql:
                      BasicBinder: WARN
management:
   endpoints:
      web:
         exposure:
            include: env,info,health
# Application's properties
message:
    userNotFound: Unable to find any user with email/contact %s, Please contact your Admin
user:
    auth:
        issuer: simple-bug
        secret: top-secret
        expiration-sec: 3600
        tokenMissing: Unable to find Authentication Token
        userTokenNotFound: Unable to find any user with %s token
    message:
        enityNotFound: User with %s name doesn't exists
bug:
    message:
        bugIdNotFound: Invalid Bug ID
        bugStatusNotFound: Invalid Bug Status
        bugTypeNotFound: Invalid Bug Type
        bugVersionNotFound: Version is mandate
        createdByNotFound: Bug Modified by details are missing
        entityNotFound: Bug with %s id doesn\'t exists
        modifiedByNotFound: Bug Modified by details are missing
---
spring:
    profiles: dev
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/simple-bug
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
management:
   endpoints:
      web:
         exposure:
            include: env,info,health,httptrace,logfile,metrics,mappings,beans

logging:
    level:
       org:
          hibernate:
             SQL: DEBUG
             type:
                descriptor:
                   sql:
                      BasicBinder: TRACE
---
spring:
    profiles: test
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        initialization-mode: never
        # Below is to make sure we don't keep our db connection open after 1 seconds of inactivity
        hikari:
           connection:
              timeout: 1000
           maximum-pool-size: 2
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
logging:
    level:
       com:
          github:
             hbothra: DEBUG
       io:
          github:
             hbothra: DEBUG
       org:
          springframework: INFO
          hibernate:
             SQL: DEBUG
             type:
                descriptor:
                   sql:
                      BasicBinder: TRACE