spring:
  profiles:
    active: "dev"
---
spring:
    profiles: dev
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/simple-bug
        username: root
        # This will make Sure for Dev enviornment data.sql never runs
        initialization-mode: never
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
                id:
                    new_generator_mappings: false

user:
   auth:
      issuer: simple-bug
      secret: top-secret
      expiration-sec: 3600

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: 'TRACE'
management:
   endpoints:
      web:
         exposure:
            include: env,info,health,httptrace,logfile,metrics,mappings,beans
---
spring:
    profiles: test
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        initialization-mode: never
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                id:
                    new_generator_mappings: false
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: 'TRACE'