INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (1,'ADMIN')
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (2,'SUPPORT')
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (3,'VENDOR')

INSERT INTO STATUS_TYPE ('TYPE_ID','STATUS_TYPE') VALUES (1,'TO_DO')
INSERT INTO STATUS_TYPE ('TYPE_ID','STATUS_TYPE') VALUES (2,'IN_PROGRESS')
INSERT INTO STATUS_TYPE ('TYPE_ID','STATUS_TYPE') VALUES (3,'FIXED')
INSERT INTO STATUS_TYPE ('TYPE_ID','STATUS_TYPE') VALUES (4,'CLOSED')
INSERT INTO STATUS_TYPE ('TYPE_ID','STATUS_TYPE') VALUES (5,'REJECTED')

INSERT INTO BUG_TYPE ('TYPE_ID','BUG_TYPE') VALUES (1,'PURCHASE')
INSERT INTO BUG_TYPE ('TYPE_ID','BUG_TYPE') VALUES (2,'INSTALLATION')
INSERT INTO BUG_TYPE ('TYPE_ID','BUG_TYPE') VALUES (3,'WARRANTY')
INSERT INTO BUG_TYPE ('TYPE_ID','BUG_TYPE') VALUES (4,'REPAIR')

INSERT INTO `USER` ('USER_ID', 'USER_NAME', 'ADDRESS_LINE_1', 'ADDRESS_LINE_2', 'ADDRESS_LINE_3', 'CONTACT', 'EMAIL', 'USER_TYPE')
VALUES (1,'ADMIN','ADMIN',NULL,NULL,'7700000000','admin@simpleBug.com',1)

INSERT INTO `BUGS` ('BUG_ID', 'BUG_TITLE', 'BUG_DESCR', 'CREATED_ON', 'CREATED_BY', 'PROJECT', 'MODIFIED_BY', 'MODIFIED_ON') 
VALUES (1,'First Bug','Default Bug',CURRENT_TIMESTAMP,1,0,1,CURRENT_TIMESTAMP)