INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE, CREATED_ON, MODIFIED_ON) VALUES (1,'ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE, CREATED_ON, MODIFIED_ON) VALUES (2,'SUPPORT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE, CREATED_ON, MODIFIED_ON) VALUES (3,'VENDOR',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)

INSERT INTO STATUS_TYPE (TYPE_ID,STATUS_TYPE, CREATED_ON, MODIFIED_ON) VALUES (1,'TO_DO',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO STATUS_TYPE (TYPE_ID,STATUS_TYPE, CREATED_ON, MODIFIED_ON) VALUES (2,'IN_PROGRESS',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO STATUS_TYPE (TYPE_ID,STATUS_TYPE, CREATED_ON, MODIFIED_ON) VALUES (3,'FIXED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO STATUS_TYPE (TYPE_ID,STATUS_TYPE, CREATED_ON, MODIFIED_ON) VALUES (4,'CLOSED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO STATUS_TYPE (TYPE_ID,STATUS_TYPE, CREATED_ON, MODIFIED_ON) VALUES (5,'REJECTED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)

INSERT INTO BUG_TYPE (TYPE_ID,BUG_TYPE, CREATED_ON, MODIFIED_ON) VALUES (1,'PURCHASE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO BUG_TYPE (TYPE_ID,BUG_TYPE, CREATED_ON, MODIFIED_ON) VALUES (2,'INSTALLATION',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO BUG_TYPE (TYPE_ID,BUG_TYPE, CREATED_ON, MODIFIED_ON) VALUES (3,'WARRANTY',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO BUG_TYPE (TYPE_ID,BUG_TYPE, CREATED_ON, MODIFIED_ON) VALUES (4,'REPAIR',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)

INSERT INTO USER (USER_ID, USER_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, CONTACT, EMAIL, PASSWD, CREATED_ON, MODIFIED_ON) VALUES (1,'ADMIN','ADMIN',NULL,NULL,'7700000000','admin@simpleBug.com','LetMeIn',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)

INSERT INTO BUGS (BUG_ID, BUG_TITLE, BUG_DESCR, CREATED_ON, CREATED_BY, PROJECT, MODIFIED_BY, MODIFIED_ON, BUG_TYPE, BUG_STATUS) VALUES (1,'First Bug','Default Bug',CURRENT_TIMESTAMP,1,0,1,CURRENT_TIMESTAMP,1,1)

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1)