INSERT INTO USER_TYPE VALUES (1,'ADMIN');
INSERT INTO USER_TYPE VALUES (2,'SUPPORT');
INSERT INTO USER_TYPE VALUES (3,'VENDOR');

INSERT INTO STATUS_TYPE VALUES (1,'TO_DO');
INSERT INTO STATUS_TYPE VALUES (2,'IN_PROGRESS');
INSERT INTO STATUS_TYPE VALUES (3,'FIXED');
INSERT INTO STATUS_TYPE VALUES (4,'CLOSED');
INSERT INTO STATUS_TYPE VALUES (5,'REJECTED');

INSERT INTO BUG_TYPE VALUES (1,'PURCHASE');
INSERT INTO BUG_TYPE VALUES (2,'INSTALLATION');
INSERT INTO BUG_TYPE VALUES (3,'WARRANTY');
INSERT INTO BUG_TYPE VALUES (4,'REPAIR');

INSERT INTO USER VALUES (1,'ADMIN','ADMIN',NULL,NULL,'7700000000','admin@simpleBug.com',1);

INSERT INTO `BUGS` VALUES (1,'First Bug','Default Bug',1,1,1,CURRENT_TIMESTAMP,1,0,1,CURRENT_TIMESTAMP);